#!/bin/bash
sudo firewall-cmd --permanent --zone=public --add-port=8529/tcp
sudo firewall-cmd --reload
cd /etc/yum.repos.d/
sudo curl -OL https://download.arangodb.com/arangodb34/RPM/arangodb.repo
sudo yum -y install arangodb3-3.4.0
sudo -i ARANGODB_DEFAULT_ROOT_PASSWORD=ARANGODBONOCI arango-secure-installation
sudo systemctl start arangodb3.service
sudo systemctl enable arangodb3.service